/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
*/

public class p002 {

	public static void main(String[] args) {

		int max = 4000000;
		int current = 0, prev1 = 2, prev2 = 1;
		int sum = 2;
		while (current < max) {
			current = prev1 + prev2;
			prev2 = prev1;
			prev1 = current;

			if (current % 2 == 0) {
				sum += current;
			}
		}

		System.out.println(sum);
	}
}
